channels:
  - conda-forge
dependencies:
  - ase =3.23.0
  - langchain =0.2.5
  - numexpr =2.10.0
  - langchain-openai =0.1.8
  - langchain-experimental =0.0.61
  - pymace =0.3.5
  - matplotlib =3.8.4
  - pandas =2.2.2
  - mendeleev =0.17.0
  - lxml =4.9.4